<?xml version="1.0" encoding="utf-8"?><Database Name="QbixTest" Class="QbixTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PAPA\SQLSERVER__2017;Initial Catalog=QbixTest;Integrated Security=True" SettingsObjectName="QbixWinFormsLinqTest.Properties.Settings" SettingsPropertyName="QbixTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Должности" Member="Должностиs">
    <Type Name="Должности">
      <Column Name="Должность_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Должность_Имя" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Должности_Должности_Навыки" Member="Должности_Навыкиs" ThisKey="Должность_Id" OtherKey="Должность_Id" Type="Должности_Навыки" />
      <Association Name="Должности_Сотрудники_Должности" Member="Сотрудники_Должностиs" ThisKey="Должность_Id" OtherKey="Должность_Id" Type="Сотрудники_Должности" />
    </Type>
  </Table>
  <Table Name="dbo.Должности_Навыки" Member="Должности_Навыкиs">
    <Type Name="Должности_Навыки">
      <Column Name="Навык_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Навык_Имя" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Должность_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Должности_Навыки_Сотрудники_Должн_Навыки" Member="Сотрудники_Должн_Навыкиs" ThisKey="Навык_Id,Должность_Id" OtherKey="Навык_Id,Должность_Id" Type="Сотрудники_Должн_Навыки" />
      <Association Name="Должности_Должности_Навыки" Member="Должности" ThisKey="Должность_Id" OtherKey="Должность_Id" Type="Должности" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Сотрудники" Member="Сотрудникиs">
    <Type Name="Сотрудники">
      <Column Name="Сотрудник_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Сотрудник_Фио" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Сотрудники_Сотрудники_Должн_Навыки" Member="Сотрудники_Должн_Навыкиs" ThisKey="Сотрудник_Id" OtherKey="Сотрудник_Id" Type="Сотрудники_Должн_Навыки" />
      <Association Name="Сотрудники_Сотрудники_Должности" Member="Сотрудники_Должностиs" ThisKey="Сотрудник_Id" OtherKey="Сотрудник_Id" Type="Сотрудники_Должности" />
    </Type>
  </Table>
  <Table Name="dbo.Сотрудники_Должн_Навыки" Member="Сотрудники_Должн_Навыкиs">
    <Type Name="Сотрудники_Должн_Навыки">
      <Column Name="Сотрудник_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Должность_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Навык_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Должности_Навыки_Сотрудники_Должн_Навыки" Member="Должности_Навыки" ThisKey="Навык_Id,Должность_Id" OtherKey="Навык_Id,Должность_Id" Type="Должности_Навыки" IsForeignKey="true" />
      <Association Name="Сотрудники_Сотрудники_Должн_Навыки" Member="Сотрудники" ThisKey="Сотрудник_Id" OtherKey="Сотрудник_Id" Type="Сотрудники" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Сотрудники_Должности" Member="Сотрудники_Должностиs">
    <Type Name="Сотрудники_Должности">
      <Column Name="Сотрудник_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Должность_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Должности_Сотрудники_Должности" Member="Должности" ThisKey="Должность_Id" OtherKey="Должность_Id" Type="Должности" IsForeignKey="true" />
      <Association Name="Сотрудники_Сотрудники_Должности" Member="Сотрудники" ThisKey="Сотрудник_Id" OtherKey="Сотрудник_Id" Type="Сотрудники" IsForeignKey="true" />
    </Type>
  </Table>
</Database>